name: Debug Repo Files

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print current path
        run: pwd

      - name: Print root files
        run: ls -la

      - name: Print all files
        run: find . -type f | sort
